#!/bin/bash

if [ -z "$1" ]; then
    echo "No GUI Required, HEADLESS=1."
    HEADLESSVal=1
else
    if [ "$1" == 2 ]; then
        TYPE="gz_x500"
    else
        TYPE="gz_tailsitter"
    fi
    HEADLESSVal=0
fi

cd $PX4_ROOT


# start communication 
MicroXRCEAgent udp4 -p 8888 &

# Start the PX4 SITL
if [ $HEADLESSVal -eq 1 ]; then
    echo "Running PX4 SITL in headless mode."
    HEADLESS=1 make px4_sitl gz_tailsitter
else
    echo "Running PX4 SITL with GUI."
    make px4_sitl $TYPE
fi
